package themes

enum class AppTheme(val backgroundImagePath: String?) {
    LIGHT(null),
    DARK(null),
    MINECRAFT("minecraft_bg_tile.png"),
    RETRO_8BIT(null),
    NEON_CYBERPUNK(null),
    PASTEL(null),
    GRADIENT(null),
    MONOCHROME(null),
    DARK_ACCENT(null),
    NATURE(null),
    RAINBOW(null),
    VINTAGE(null),

    PIXEL_ART(null),
    FUTURISTIC_HUD(null),
    MIDNIGHT_BLUE(null),
    WOODLAND("wood_bg.png"),
    OCEANIC("ocean_bg.png"),
    DESERT_SUNSET(null),
    TERMINAL_GREEN(null),
    SOLARIZED_LIGHT(null),
    SOLARIZED_DARK(null),
    STARRY_NIGHT("stars_bg.png"),
    SUNSET_GLOW(null),
    MORNING_FRESH(null),
    COZY_CABIN(null),
    LUSH_MEADOW(null),
    ELECTRIC_LIME(null),
    DEEP_TWILIGHT(null),
    CANDY_PINK(null),
    COOL_AQUA(null),
    COTTON_CANDY(null),
    SPACE_RETRO(null),
    BUBBLEGUM_POP(null),
    CHOCOLATE_LATTE(null),
    SKYLINE_PURPLE(null),
    SOFT_MINT(null),
    GOLDEN_HOUR(null),
    FROSTED_BLUE(null),
    LAVENDER_FIELD(null),
    TOY_BOX(null),
}